sudo: required
services:
  - docker
  - redis-server
language: go
go:
  - 1.9.2
git:
  depth: 1000
addons:
  apt:
    packages: rpm
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9992cd0d36a6ba9bb40b
    on_success: change
    on_failure: always
    on_start: never
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls
install:
  - make test
  - make lint
  - goveralls -coverprofile=coverage.txt -service=travis-ci
before_script:
  - gem install fpm
script:
  - make packages
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: releases
    api_key:
      secure: MrD5ER9P/vJoXB5eNbjMI/rKz8TGS9fannjO+K5/wkFxZhLI0JeaRIxjXv30kk9Da6Blkk7AE9dz3tkkLOl82oXS6bKZy4ZCZrTG2NAV9EYzM+LQQTnVzkpUiane4GMKhj4e3Gu1YzJulA/Emec9Ba5TOxp2i5+K3PVkwZcSkMaleIJjzrJWFDaeq6HGiE/43puCVszCFg8vPSTR6zUZhus7qBixpFOmHpD4Kx5wZKUmsSm/iiFIaMYZjVGj3xBIUjfwDKqJkuIJOD8wPFeRhV8hCVuu7uN45lIwUTrzGbzOPPt7/zTpfJodwIS3FmgGF+pMRp2u2ny6xZmdRUwk/dR43ou7hSLb9FHNr6ZWl2cB5VT9p5lAe5wlrRRH6USUF7/Y1tgJrCtEHWPJZPfK4nQ+q0Zx7hs2QNCKmW6TO09JdtZuD09RksoEiG5RCpVZUBJW3Fn7aUkCUUFnXyvRc1IgxcBdVo6DjNTR9LLwwq1iEIXe5ultiMhjbVI2+tawSQbl8vEphOcz5xUebIqK7Yl46txHXHzzYCC0WqGaxOGviHPM6yqvvWGmonj/B57ebKJkKGN3bfZeZ+vn66FrRuEif81zBgnje/va+gQTLckNnYCudZxnezMSF5bk+zYOwDtsyxSO7QEPLTP8zdCQoSvaoAH+4BVU+wcleSNF7zU=
    file_glob: true
    file:
      - build/moira*.tar.gz
      - build/moira*.rpm
      - build/moira*.deb
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script:
      - make docker_feature_images
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^feature.*$
  - provider: script
    script:
      - make docker_develop_images
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script:
      - make docker_latest_images
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script:
      - make docker_release_images 
    skip_cleanup: true
    on:
      tags: true
