sudo: required
services:
  - docker
  - redis-server
language: go
go:
  - 1.14
git:
  depth: 1000
addons:
  apt:
    packages: rpm
notifications:
  slack:
    secure: ZzUtFRyc8lJfO1+qVf/oWd3PK7x3gb/MiC4U4atMmHQX2Vr+zHBZiVijK91sBhozJ7oP0GWkgmVqbKG5GDqEGur7Nt0aNfx9GU2d6dqvFeQGY910EDK9wmdSCMk3gfZ1d1ur2NmkyxNRlbDnlHIGdTgzqrKsvlhk9BxLw1D1/1Ap57pZxkCGsu9VP/NUZhywo8T7HhLyarKO3iBhNFQqR1ifVHS0KjDS6p+4JXg74Ufq91WEWw+/L6NMSO9DPDu1i4HHp6rNE2rjR/0O5Nl8AtIApFOpdjh/9vNv9Mm/S/8PpfPo4nuhL1YGsdCd2dRf9owMQVfVgxZVNK/wyt+NxbG3IuuUf0Nve4wgnKLBaiqLgHw++uLS/+jADY/d9EN4Pb0oLQ5S0cKhFjJ63B3z0MsGoYkZCvpBvHKcOt2zWmiK+ugx2Er2KRSonGYpHHLdGxvlUFuWf5vBh/dnyxYMtnbtryW0xIabHKkXT2lr00xdNRNYYZPAfN0Rdp6BJjzel1yPnj71aNW7qmauMqiCZDjjiLZ6nvL7WEvsJoQyz84LNSv9zQK2XEaGF3bA8OOf6Mse25PWoCUjHwOQQncdLKTb0/RQOWykLAHIjagKotXV8RtTNXN3kYQwUAst7cYESYeTlqB510dKge74R6rQOrrMCInGuDfzZ3+duqVXip4=
    on_success: never
    on_failure: always
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - gem install fpm
install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls
  - make install-reviewdog
before_script:
  - make reviewdog REVIEWDOG_RUNNERS=golangci-$([[ "$TRAVIS_PULL_REQUEST" = "false" ]] && echo "branch" || echo "pr")
  - make test
  - goveralls -coverprofile=coverage.txt -service=travis-ci || true
script:
  - if [[ ! -z "$TRAVIS_TAG" ]]; then make packages; fi
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: releases
    api_key:
      secure: MrD5ER9P/vJoXB5eNbjMI/rKz8TGS9fannjO+K5/wkFxZhLI0JeaRIxjXv30kk9Da6Blkk7AE9dz3tkkLOl82oXS6bKZy4ZCZrTG2NAV9EYzM+LQQTnVzkpUiane4GMKhj4e3Gu1YzJulA/Emec9Ba5TOxp2i5+K3PVkwZcSkMaleIJjzrJWFDaeq6HGiE/43puCVszCFg8vPSTR6zUZhus7qBixpFOmHpD4Kx5wZKUmsSm/iiFIaMYZjVGj3xBIUjfwDKqJkuIJOD8wPFeRhV8hCVuu7uN45lIwUTrzGbzOPPt7/zTpfJodwIS3FmgGF+pMRp2u2ny6xZmdRUwk/dR43ou7hSLb9FHNr6ZWl2cB5VT9p5lAe5wlrRRH6USUF7/Y1tgJrCtEHWPJZPfK4nQ+q0Zx7hs2QNCKmW6TO09JdtZuD09RksoEiG5RCpVZUBJW3Fn7aUkCUUFnXyvRc1IgxcBdVo6DjNTR9LLwwq1iEIXe5ultiMhjbVI2+tawSQbl8vEphOcz5xUebIqK7Yl46txHXHzzYCC0WqGaxOGviHPM6yqvvWGmonj/B57ebKJkKGN3bfZeZ+vn66FrRuEif81zBgnje/va+gQTLckNnYCudZxnezMSF5bk+zYOwDtsyxSO7QEPLTP8zdCQoSvaoAH+4BVU+wcleSNF7zU=
    file_glob: true
    file:
      - build/moira*.tar.gz
      - build/moira*.rpm
      - build/moira*.deb
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script:
      - make docker_feature_images GIT_BRANCH="${TRAVIS_BRANCH////-}"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH =~ ^(feature|hotfix).*$
  - provider: script
    script:
      - make docker_nightly_images
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script:
      - make docker_release_images
    skip_cleanup: true
    on:
      tags: true
